CREATE TABLE Fornecedor (
    Fcodigo INTEGER PRIMARY KEY,
    Fnome VARCHAR(50) NOT NULL,
    Status VARCHAR(50) DEFAULT 'Ativo',
    Cidade VARCHAR(100)
);

SELECT * FROM Fornecedor;

CREATE TABLE Peca (
    Pcodigo INT PRIMARY KEY,
    Pnome VARCHAR(100) NOT NULL,
    Cor VARCHAR(100) NOT NULL,
    Peso DECIMAL(10,2) NOT NULL,
    Cidade VARCHAR(100) NOT NULL
);

SELECT * FROM Peca;

CREATE TABLE Instituicao (
    Icodigo INT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL
);

SELECT * FROM Instituicao;

CREATE TABLE Projeto (
    PRcodigo INT PRIMARY KEY,
    PRnome VARCHAR(100) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    Icodigo INTEGER,
    FOREIGN KEY (Icodigo) REFERENCES Instituicao(Icodigo)
);

SELECT * FROM Projeto;

CREATE TABLE Fornecimento (
    Fcodigo INT,
    Pcodigo INT,
    PRcodigo INT,
    Quantidade INT,
    PRIMARY KEY (Fcodigo, Pcodigo, PRcodigo),
    FOREIGN KEY (Fcodigo) REFERENCES Fornecedor(Fcodigo),
    FOREIGN KEY (Pcodigo) REFERENCES Peca(Pcodigo),
    FOREIGN KEY (PRcodigo) REFERENCES Projeto(PRcodigo)
);

SELECT * FROM Fornecimento;


SELECT * FROM Fornecedor;
SELECT * FROM Peca;
SELECT * FROM Instituicao;
SELECT * FROM Projeto;
SELECT * FROM Fornecimento;

-- digogo version

---Correção Exercicios

CREATE TABLE FORNECEDOR(
    FCODIGO INTEGER PRIMARY KEY,
    FNOME VARCHAR(50) NOT NULL,
    STATUS VARCHAR(10) DEFAULT 'ATIVO',
    CIDADE VARCHAR(20)
);

SELECT * FROM FORNECEDOR;

CREATE TABLE PECA(
    PCODIGO INTEGER PRIMARY KEY,
    PNOME VARCHAR(50) NOT NULL,
    COR VARCHAR(10) NOT NULL,
    PESO NUMERIC(7,2) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL
);

SELECT * FROM PECA;

CREATE TABLE INSTITUCAO(
    ICODIGO INTEGER PRIMARY KEY,
    INOME VARCHAR(50) NOT NULL
);

SELECT * FROM INSTITUCAO;

CREATE TABLE PROJETOS(
    PRCODIGO INTEGER PRIMARY KEY,
    PRNOME VARCHAR(50) NOT NULL,
    PRCIDADE VARCHAR(20) NOT NULL,
    ICODIGO INTEGER,
    FOREIGN KEY (ICODIGO) REFERENCES INSTITUCAO
);

SELECT * FROM PROJETOS;

CREATE TABLE FORNECIMENTO(
    ID SERIAL PRIMARY KEY,
    FCODIGO INTEGER,
    PCODIGO INTEGER,
    PRCODIGO INTEGER,
    QUANTIDADE INTEGER,
    FOREIGN KEY(FCODIGO) REFERENCES FORNECEDOR,
    FOREIGN KEY(PCODIGO) REFERENCES PECA,
    FOREIGN KEY(PRCODIGO) REFERENCES PROJETOS
);

SELECT * FROM FORNECIMENTO;

-- ALTERAÇÕES (PARTE 02)

ALTER TABLE PROJETO
	DROP FOREIGN KEY ICODIGO;

ALTER TABLE PROJETOS
	DROP COLUMN ICODIGO;

DROP TABLE INSTITUCAO;

-- CRIAÇÃO DA TABELA CIDADE
CREATE TABLE CIDADE(
    CCOD INT NOT NULL,
    CNOME VARCHAR(30) NOT NULL,
    UF CHAR(2) NOT NULL,
    PRIMARY KEY (CCOD)
);

SELECT * FROM CIDADE;

-- ALTERAÇÃO NA TABELA FORNECEDOR
SELECT * FROM FORNECEDOR;

ALTER TABLE FORNECEDOR
	DROP COLUMN CIDADE;

ALTER TABLE FORNECEDOR
	ADD COLUMN FONE BIGINT NOT NULL;

ALTER TABLE FORNECEDOR
    ALTER COLUMN FONE TYPE BIGINT;

ALTER TABLE FORNECEDOR
	ADD COLUMN CCOD INT NOT NULL;

ALTER TABLE FORNECEDOR
	ADD CONSTRAINT FK_CCOD_FORNECEDOR
    FOREIGN KEY (CCOD) REFERENCES CIDADE (CCOD);

ALTER TABLE FORNECEDOR
	DROP CONSTRAINT FK_CCOD_FORNECEDOR
    FOREIGN KEY (CCOD) REFERENCES CIDADE (CCOD);

SHOW CREATE TABLE FORNECEDOR;

-- ALTERAÇÃO NA TABELA PECA
SELECT * FROM TBL_PECA;

ALTER TABLE TBL_PECA
	DROP COLUMN PCIDADE;

ALTER TABLE TBL_PECA 
	ADD COLUMN CCOD INT NOT NULL;

ALTER TABLE TBL_PECA
	ADD CONSTRAINT FK_CCOD_PECA
    FOREIGN KEY (CCOD) REFERENCES TBL_CIDADE (CCOD);

-- ALTERAÇÃO NA TABELA PROJETO
SELECT * FROM TBL_PROJETO;

ALTER TABLE TBL_PROJETO
	DROP COLUMN CIDADE;

ALTER TABLE TBL_PROJETO
	ADD COLUMN CCOD INT NOT NULL;

ALTER TABLE TBL_PROJETO
	ADD CONSTRAINT FK_CCOD_PROJETO
    FOREIGN KEY (CCOD) REFERENCES TBL_CIDADE (CCOD);